Add tutorials on code generation and RK order conditions to docs.
ranocha/BSeries.jl pull request #101
Opened 2023-02-27 02:18 UTC by ketch

In this PR I added two tutorials, based on user requests:

- Generation of C code using symbolics.jl.  It would be nice if we could also use Sympy's code generation utilities, but I can't find a way to access those from SymPy.jl.  I've raised an issue over there.
- Generation of RK order conditions for a RK method with unspecified coefficients.

For both of these, I've also included a Jupyter notebook source.

I don't know how to add these to the table of contents of the docs, or whether that will happen automatically.

2023-02-27 02:22 UTC, ketch commented
For the order conditions tutorial, it would be nice if we could also have output where the indices of A and b appear properly as subscripts in the output (like they do when you print out the matrices themselves) but I couldn't find a way to do that.

2023-02-27 05:13 UTC, ranocha commented
Thanks a lot, I will have a look at it.

- You need to add the new tutorials to 
  https://github.com/ranocha/BSeries.jl/blob/3a4510816975eda6b0ea39194598ad6e1cf92456/docs/make.jl#L53-L59
  to include them in the docs and the table of contents.
- The preview of the new docs from this PR is available at https://ranocha.de/BSeries.jl/previews/PR101/

2023-02-27 05:28 UTC, ranocha requested changes
Thanks a lot! Please find some suggestions below.

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +# Runge-Kutta Order conditions
```suggestion
# Runge-Kutta order conditions
```
Capitalizing "Order" but not "conditions" looked a bit strange to me.

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +
There are several symbolic packages you can use. Here, we will use SymPy.jl.

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +```
If you turn these parts into (named) example blocks (from Documenter.jl) as in
https://github.com/ranocha/BSeries.jl/blob/3a4510816975eda6b0ea39194598ad6e1cf92456/docs/src/tutorials/bseries_basics.md?plain=1#L7-L13
the code will be executed whenever we build the docs to ensure that everything still works. 


````suggestion
```@example bseries-RK-order-conditions
using BSeries, SymPy, Latexify

s = 4  # Stages
p = 4  # Desired order of accuracy

A = Array{Sym,2}(undef, s, s)
b = Array{Sym,1}(undef, s)
c = Array{Sym,1}(undef, s);
```
````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +```
Continuing the examples block structure from above

````suggestion
```@example bseries-RK-order-conditions
for i in 1:s
    b[i] = symbols("b$i", real = true)
    for j in 1:i-1
        A[i, j] = symbols("a$i$j", real = true)
    end
    for j in i:s
        A[i, j] = 0
    end
end

for i in 1:s
    c[i] = 0
    for j in 1:i-1
        c[i] += A[i, j]
    end
end
```
````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +```
It is common to use lowercase for variables in Julia.

````suggestion
```@example bseries-RK-order-conditions

rk3 = bseries(A, b, c, p)
exact = ExactSolution(rk3)
error = rk3 - exact
```
````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +
```suggestion
```
This isn't necessary anymore since it will be generated by the code above.

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +The output above is truncated in the Jupyter notebook.  We can see the full expressions as follows:
```suggestion
The output above is truncated.  We can see the full expressions as follows:
```

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +
````suggestion
```@example bseries-RK-order-conditions
for (tree, order_condition) in error
    println(order_condition)
end
```

````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/code_generation.md
> +First, we generate the B-series that we want work with.  Here we take a generics 2nd-order RK method and generate terms only up to 3rd order, in order to work with the leading truncation error.
```suggestion
First, we generate the B-series that we want work with.  Here we take a generic 2nd-order RK method and generate terms only up to 3rd order, in order to work with the leading truncation error.
```

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/code_generation.md
> +```
````suggestion
```@example code-generation
using BSeries, Latexify, Symbolics

@variables α
A = [0 0; 1/(2*α) 0]
b = [1-α, α]
c = [0, 1/(2*α)]

rk22 = bseries(A, b, c, 3)
exact = ExactSolution(rk22)
truncation_error = rk22 - exact
```
````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/code_generation.md
> +```
````suggestion
```@example code-generation
@variables h # time step size
@variables p q # variables of the ODE
f = [p * (2 - q), q * (p - 1)]

du = evaluate(f, [p, q], h, truncation_error)
```
````

2023-02-27 05:28 UTC, ranocha commented on docs/src/tutorials/code_generation.md
> +```
````suggestion
```@example code-generation
build_function(du, α, p, q, h, target = Symbolics.CTarget())
```
````

2023-02-27 09:51 UTC, ketch commented
Thanks!  I followed all your suggestions.  Hopefully this is ready now.

2023-02-28 02:36 UTC, ketch commented
The docs are failing to build, and I get the same error when building them locally, but I don't understand why.   The output from the build is not very clear to me.  I think the key is these lines:

```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
  [1] getindex
    @ ./array.jl:861 [inlined]
  [2] (::SymPy.var"#2#5"{Vector{SymPy.Sym}})(i::Int64)
```
It seems clear that this indicates an issue with `RK_order_conditions.md`, which has these lines:

```
A = Array{Sym,2}(undef, s, s)
b = Array{Sym,1}(undef, s)
c = Array{Sym,1}(undef, s);
```
However, all the values of these arrays are later defined before they are used.  I executed all the code in that file in a julia prompt and it ran just fine.  It also (of course) runs fine in the corresponding Jupyter notebook.  @ranocha do you have an idea what could be causing this error?

2023-02-28 15:16 UTC, ranocha commented on docs/src/tutorials/RK_order_conditions.md
> +```@example bseries-RK-order-conditions
```suggestion

```

2023-02-28 15:18 UTC, ranocha approved these changes
Thanks! I hope I fixed the error.

2023-02-28 16:39 UTC, merged