Pull Request for CSRK code
ranocha/BSeries.jl pull request #140
Opened 2023-06-20 15:11 UTC by Sondar74

2023-06-20 15:41 UTC, ketch commented on src/CSRK.jl
> +# This function generates a polinomial
Remember to use English, here and throughout.

2023-06-21 06:10 UTC, ranocha requested changes

2023-06-21 06:10 UTC, ranocha commented on src/BSeries.jl
> +
Please clean up this PR. It looks to me like there is a huge amount of changes that is not really related to what you would like to do in this PR - in particular all changes to this file as well as `src/Energy_Preserving.jl`?

2023-06-21 06:10 UTC, ranocha commented on src/Energy_Preserving.jl
> +module Energy_Preserving
Shouldn't be here?

2023-06-21 06:10 UTC, ranocha commented on test/runtests.jl
> +    #We test the code Energy_Preserving.jl using the function 'OrderMethod(A,b) for a given
Should also be available in `main` in the latest version?

2023-06-21 06:12 UTC, ranocha commented
If all that is new in this PR is contained in `src/CSRK.jl`, it may be simpler to just create a new PR from a clean base, adding only this single file.
Again, please consider incorporating the new functionality into the package such that it will be available when `using BSeries`

2023-06-21 08:52 UTC, Sondar74 commented
> If all that is new in this PR is contained in `src/CSRK.jl`, it may be simpler to just create a new PR from a clean base, adding only this single file. Again, please consider incorporating the new functionality into the package such that it will be available when `using BSeries`

You are right. I will make another pull request only with the BSeries.jl file changed

2023-06-25 10:23 UTC, ranocha commented
Are you working in this PR or in #141?

2023-06-25 11:44 UTC, Sondar74 commented
> Are you working in this PR or in #141?

I had problems running the updated code in the other one. Maybe it will be better to keep on working with this one. 
I created the `struct` 'ContinuousRungeKuttaMethod' and a function `CSRK` (an example of its functionality is included in the description of this PR).

2023-06-25 11:58 UTC, ranocha commented
Ok. Please close the PR you don't want to continue working on. And please resolve the conflicts in the PR you are working on.

2023-06-25 12:08 UTC, ranocha requested changes

2023-06-25 12:08 UTC, ranocha commented on Project.toml
> -name = "BSeries"
You shouldn't delete this file

2023-06-25 12:08 UTC, ranocha commented on src/BSeries.jl
> +function is_energy_preserving(A,b,s)
This still looks like a merge conflict

2023-06-25 12:08 UTC, ranocha commented on test/Project.toml
> -[deps]
You shouldn't delete this file

2023-06-25 12:08 UTC, ranocha commented on test/runtests.jl
> -using Test
You shouldn't delete this file

2023-06-27 09:13 UTC, closed without merging